#!/usr/bin/env bash
# Regenerate docs/updatePlugins.xml so it points at the just-released
# version. Called from .github/workflows/release.yml after the GitHub
# Release is created, so the zip URL is already live.
#
# Reads:
#   - $1                              tag name (e.g. "v0.1.1")
#   - plugin/gradle.properties        plugin id (single source of truth)
#   - REPO_URL env var (optional)     defaults to the canonical repo URL
#
# Writes:
#   - docs/updatePlugins.xml          replaces with single-entry XML
#                                     pointing at the new release zip
#
# Single-entry vs multi-version: we keep just one <plugin> entry per
# release. JetBrains IDEs install the highest version that matches the
# build range, and v0.1.x all share since-build=261, so older entries
# are dead weight. If we ever need to support multiple IDE-version
# branches simultaneously, switch to multi-entry generation here.

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <tag>" >&2
  exit 64
fi

TAG="$1"
VERSION="${TAG#v}"
REPO_URL="${REPO_URL:-https://github.com/kouko/intellij-dbtree}"

PLUGIN_ID=$(awk -F'= *' '/^pluginId[[:space:]]*=/ { print $2; exit }' \
              plugin/gradle.properties | tr -d '[:space:]')
SINCE_BUILD=$(awk -F'= *' '/^pluginSinceBuild[[:space:]]*=/ { print $2; exit }' \
                plugin/gradle.properties | tr -d '[:space:]')
ZIP_URL="${REPO_URL}/releases/download/${TAG}/dbtree-${VERSION}.zip"

cat > docs/updatePlugins.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Custom plugin repository descriptor served by GitHub Pages.

  Users add the GitHub-Pages-hosted URL of this file to JetBrains IDE:
    Settings → Plugins → ⚙ → Manage Plugin Repositories…

  Once added, the IDE can install / auto-update dbtree the same way it
  handles Marketplace plugins, AND Settings Sync will reinstall it on
  other machines that share the repository URL.

  This file is regenerated by .github/workflows/release.yml on each
  tag push — manual edits are overwritten.
-->
<plugins>
  <plugin id="${PLUGIN_ID}"
          url="${ZIP_URL}"
          version="${VERSION}">
    <idea-version since-build="${SINCE_BUILD}"/>
    <name>dbtree</name>
    <vendor email="kouko.d@gmail.com" url="${REPO_URL}">kouko</vendor>
    <description><![CDATA[dbt model lineage with column-level tracing for JetBrains IDEs.]]></description>
  </plugin>
</plugins>
EOF

echo "Wrote docs/updatePlugins.xml for ${TAG} (${VERSION})"
